// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type DocumentInput struct {
	Title       string `json:"title"`
	Description string `json:"description"`
	File        string `json:"file"`
}

type GraphDocument struct {
	ID          string `json:"id"`
	Title       string `json:"title"`
	Description string `json:"description"`
	File        string `json:"file"`
}

type GraphUser struct {
	ID       string `json:"id"`
	Username string `json:"username"`
	Password string `json:"password"`
	Email    string `json:"email"`
}
